import { useState, useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { articleActions } from '../stores/articleReducer';
import Head from 'next/head';
import Backdrop from '../components/Ui/Backdrop';
import HeaderLayout from '../components/Layouts/HeaderLayout';
import MainLayout from '../components/Layouts/MainLayout';
import Navbar from '../components/Header/Navbar';

import axios from 'axios';

export default function Home(props) {
  const dispatch = useDispatch();
  const [show, setShow] = useState(false);
  const showHandler = () => {
    setShow((prev) => !prev);
  };
  const data = props.articles.articles;

  useEffect(() => {
    if (!data) {
      dispatch(articleActions.pending());
    } else {
      dispatch(articleActions.success(data));
    }
  }, [data]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {show && <Backdrop show={show} onShow={showHandler} />}
      <Navbar onShow={showHandler} />
      <HeaderLayout />
      <MainLayout />
    </div>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get('http://localhost:3000/api/articles');

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      articles: data,
    },
  };
}
